patch:
  switches:
    - name: ascii_mode
      reset: 1                 #
      states: ["ä¸­æ–‡", "è¥¿æ–‡"]
    - name: full_shape
      states: ["åŠè§’", "å…¨è§’"]
    - name: zh_simp                      # ç¹ç®€è½¬æ¢
      reset: 1
      states: ["æ¼¢å­—", "æ±‰å­—"]
    - name: show_emoji
      reset: 1
      states: [ "ğŸˆšï¸ï¸\uFE0E", "ğŸˆ¶ï¸ï¸\uFE0F" ]


  engine/filters:
      - simplifier
      - simplifier@emoji_conversion
      - uniquifier
      - charset_filter@gbk              # GBK è¿‡æ»¤
      - single_char_filter
      
  emoji_conversion:
    opencc_config: emoji.json
    option_name: show_emoji
    tags: abc

# è‡ªå®šä¹‰ç¬¦å·å¼•ç”¨
  'punctuator/import_preset': symbols
  'recognizer/patterns/punct': "^/([a-z]+|[0-9])$"

  recognizer:
    patterns:
      html: "^<[a-z]+>$"
      url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$"
      email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
      uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
 


#  è½½å…¥æ‰©å±•è¯åº“
  "translator/dictionary": luna_pinyin.extended
#  æ‹¼å†™çº é”™
  "translator/enable_correction": true
